import Austin_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Austin_2021_Month07_species_sectoral_breakdown_conservative.json';
import Baltimore_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Baltimore_2021_Month07_species_sectoral_breakdown_conservative.json';
import Boston_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Boston_2021_Month07_species_sectoral_breakdown_conservative.json';
import Charlotte_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Charlotte_2021_Month07_species_sectoral_breakdown_conservative.json';
import Chicago_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Chicago_2021_Month07_species_sectoral_breakdown_conservative.json';
import Columbus_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Columbus_2021_Month07_species_sectoral_breakdown_conservative.json';
import Dallas_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Dallas_2021_Month07_species_sectoral_breakdown_conservative.json';
import Denver_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Denver_2021_Month07_species_sectoral_breakdown_conservative.json';
import Detroit_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Detroit_2021_Month07_species_sectoral_breakdown_conservative.json';
import El_Paso_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/El_Paso_2021_Month07_species_sectoral_breakdown_conservative.json';
import Fort_Worth_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Fort_Worth_2021_Month07_species_sectoral_breakdown_conservative.json';
import Houston_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Houston_2021_Month07_species_sectoral_breakdown_conservative.json';
import Indianapolis_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Indianapolis_2021_Month07_species_sectoral_breakdown_conservative.json';
import Jacksonville_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Jacksonville_2021_Month07_species_sectoral_breakdown_conservative.json';
import Las_Vegas_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Las_Vegas_2021_Month07_species_sectoral_breakdown_conservative.json';
import Los_Angeles_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Los_Angeles_2021_Month07_species_sectoral_breakdown_conservative.json';
import Louisville_Jefferson_County_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Louisville-Jefferson_County_2021_Month07_species_sectoral_breakdown_conservative.json';
import Memphis_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Memphis_2021_Month07_species_sectoral_breakdown_conservative.json';
import Nashville_Davidson_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Nashville-Davidson_2021_Month07_species_sectoral_breakdown_conservative.json';
import New_York_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/New_York_2021_Month07_species_sectoral_breakdown_conservative.json';
import Oklahoma_City_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Oklahoma_City_2021_Month07_species_sectoral_breakdown_conservative.json';
import Philadelphia_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Philadelphia_2021_Month07_species_sectoral_breakdown_conservative.json';
import Phoenix_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Phoenix_2021_Month07_species_sectoral_breakdown_conservative.json';
import Portland_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Portland_2021_Month07_species_sectoral_breakdown_conservative.json';
import San_Antonio_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/San_Antonio_2021_Month07_species_sectoral_breakdown_conservative.json';
import San_Diego_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/San_Diego_2021_Month07_species_sectoral_breakdown_conservative.json';
import San_Francisco_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/San_Francisco_2021_Month07_species_sectoral_breakdown_conservative.json';
import San_Jose_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/San_Jose_2021_Month07_species_sectoral_breakdown_conservative.json';
import Seattle_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Seattle_2021_Month07_species_sectoral_breakdown_conservative.json';
import Washington_2021_Month07_species_sectoral_breakdown_conservative from '../data/gra2pes/Washington_2021_Month07_species_sectoral_breakdown_conservative.json';

export const GRA2PES_GEOJSON: Record<string, any> = {
  "Austin_2021_Month07_species_sectoral_breakdown_conservative": Austin_2021_Month07_species_sectoral_breakdown_conservative,
  "Baltimore_2021_Month07_species_sectoral_breakdown_conservative": Baltimore_2021_Month07_species_sectoral_breakdown_conservative,
  "Boston_2021_Month07_species_sectoral_breakdown_conservative": Boston_2021_Month07_species_sectoral_breakdown_conservative,
  "Charlotte_2021_Month07_species_sectoral_breakdown_conservative": Charlotte_2021_Month07_species_sectoral_breakdown_conservative,
  "Chicago_2021_Month07_species_sectoral_breakdown_conservative": Chicago_2021_Month07_species_sectoral_breakdown_conservative,
  "Columbus_2021_Month07_species_sectoral_breakdown_conservative": Columbus_2021_Month07_species_sectoral_breakdown_conservative,
  "Dallas_2021_Month07_species_sectoral_breakdown_conservative": Dallas_2021_Month07_species_sectoral_breakdown_conservative,
  "Denver_2021_Month07_species_sectoral_breakdown_conservative": Denver_2021_Month07_species_sectoral_breakdown_conservative,
  "Detroit_2021_Month07_species_sectoral_breakdown_conservative": Detroit_2021_Month07_species_sectoral_breakdown_conservative,
  "El_Paso_2021_Month07_species_sectoral_breakdown_conservative": El_Paso_2021_Month07_species_sectoral_breakdown_conservative,
  "Fort_Worth_2021_Month07_species_sectoral_breakdown_conservative": Fort_Worth_2021_Month07_species_sectoral_breakdown_conservative,
  "Houston_2021_Month07_species_sectoral_breakdown_conservative": Houston_2021_Month07_species_sectoral_breakdown_conservative,
  "Indianapolis_2021_Month07_species_sectoral_breakdown_conservative": Indianapolis_2021_Month07_species_sectoral_breakdown_conservative,
  "Jacksonville_2021_Month07_species_sectoral_breakdown_conservative": Jacksonville_2021_Month07_species_sectoral_breakdown_conservative,
  "Las_Vegas_2021_Month07_species_sectoral_breakdown_conservative": Las_Vegas_2021_Month07_species_sectoral_breakdown_conservative,
  "Los_Angeles_2021_Month07_species_sectoral_breakdown_conservative": Los_Angeles_2021_Month07_species_sectoral_breakdown_conservative,
  "Louisville-Jefferson_County_2021_Month07_species_sectoral_breakdown_conservative": Louisville_Jefferson_County_2021_Month07_species_sectoral_breakdown_conservative,
  "Memphis_2021_Month07_species_sectoral_breakdown_conservative": Memphis_2021_Month07_species_sectoral_breakdown_conservative,
  "Nashville-Davidson_2021_Month07_species_sectoral_breakdown_conservative": Nashville_Davidson_2021_Month07_species_sectoral_breakdown_conservative,
  "New_York_2021_Month07_species_sectoral_breakdown_conservative": New_York_2021_Month07_species_sectoral_breakdown_conservative,
  "Oklahoma_City_2021_Month07_species_sectoral_breakdown_conservative": Oklahoma_City_2021_Month07_species_sectoral_breakdown_conservative,
  "Philadelphia_2021_Month07_species_sectoral_breakdown_conservative": Philadelphia_2021_Month07_species_sectoral_breakdown_conservative,
  "Phoenix_2021_Month07_species_sectoral_breakdown_conservative": Phoenix_2021_Month07_species_sectoral_breakdown_conservative,
  "Portland_2021_Month07_species_sectoral_breakdown_conservative": Portland_2021_Month07_species_sectoral_breakdown_conservative,
  "San_Antonio_2021_Month07_species_sectoral_breakdown_conservative": San_Antonio_2021_Month07_species_sectoral_breakdown_conservative,
  "San_Diego_2021_Month07_species_sectoral_breakdown_conservative": San_Diego_2021_Month07_species_sectoral_breakdown_conservative,
  "San_Francisco_2021_Month07_species_sectoral_breakdown_conservative": San_Francisco_2021_Month07_species_sectoral_breakdown_conservative,
  "San_Jose_2021_Month07_species_sectoral_breakdown_conservative": San_Jose_2021_Month07_species_sectoral_breakdown_conservative,
  "Seattle_2021_Month07_species_sectoral_breakdown_conservative": Seattle_2021_Month07_species_sectoral_breakdown_conservative,
  "Washington_2021_Month07_species_sectoral_breakdown_conservative": Washington_2021_Month07_species_sectoral_breakdown_conservative,
};
