name: Update data on a schedule cron

on:
    schedule:
      - cron: '*/10 * * * *' # Every 10 min

jobs:
  update-data:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository and create a pull request
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      # Downloads and extracts the files to the respective directory
      - name: Run the data download script
        run: |
         echo "That is it"
